name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PNPM
        run: npm install -g pnpm  

      - name: Cache PNPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store 
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile  

      - name: Build Next.js App
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: pnpm run build  

      - name: Ensure `.next/cache` Exists
        run: mkdir -p .next/cache

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: nextjs-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: nextjs-${{ runner.os }}-

      - name: Deploy to Vercel (Production)
        run: |
          npm i -g vercel  
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
